name: "Publish prerelease v-birthday"

on:
  workflow_dispatch:
    inputs:
      type:
        description: "version type (prerelease for bumping pre-release version):"
        required: true
        type: choice
        default: "prerelease"
        options:
          - prepatch
          - preminor
          - premajor
          - prerelease
      tag:
        required: true
        description: 'tag ("beta" or "alpha"):'
        type: choice
        default: "beta"
        options:
          - beta
          - alpha
      custom_version:
        description: 'custom version: x.y.z (without "v")'
        required: false

run-name: Publish ${{ inputs.type }} ${{ inputs.custom_version }} (tag ${{ inputs.tag }})

jobs:
  publish:
    concurrency: ci-gh-pages
    outputs:
      release_tag: ${{ steps.updated_version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          always-auth: true
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Set Git credentials
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"

      - name: Bump by version type
        if: ${{ !github.event.inputs.custom_version }}
        run: yarn workspace @vkontakte/vkui version --${{ github.event.inputs.type }} --preid ${{ github.event.inputs.tag }} --no-commit-hooks

      - name: Bump by custom version
        if: ${{ github.event.inputs.custom_version }}
        run: yarn workspace @vkontakte/vkui version --new-version ${{ github.event.inputs.custom_version }} --no-commit-hooks

      - name: Pushing changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Save updated package version to env
        id: updated_version
        run: echo "version=$(yarn run --silent package:version)" >> $GITHUB_OUTPUT

  close_milestone:
    needs: ["publish"]
    runs-on: ubuntu-latest
    steps:
      - name: Close milestone, comment on issues and release notes
        uses: BlackySoul/guthub_actions_test/.github/actions/close-milestone@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          releaseTag: ${{ needs.publish.outputs.release_tag }}
